Add 5.1.0 scripts

diff --git a/root-fs/app/bin/run-one-shot-update-scripts b/root-fs/app/bin/run-one-shot-update-scripts
--- a/root-fs/app/bin/run-one-shot-update-scripts
+++ b/root-fs/app/bin/run-one-shot-update-scripts
@@ -7,5 +7,27 @@ set -o pipefail
 type=$1
 scriptDir=/app/bin/$type.d
 logDir=/data/bluespice/logs/$type
+timestamp=$(date +%Y%m%d%H%M%S)
 
+echo "Running $type scripts"
 
+for f in "$scriptDir"/*; do
+	scriptName=$(basename $f)
+	logFile=/data/bluespice/logs/$type/$scriptName.log
+	errorLogFile=/data/bluespice/logs/$type/$scriptName.$timestamp.error.log
+	if [ -f "$logFile" ]; then
+		continue
+	fi
+
+	if [ -f "$f" ]; then
+		echo ""
+		echo "$f"
+		$f \
+			| tee -a $logFile
+		if [ $? -ne 0 ]; then
+			echo "Error running $f"
+			mv $logFile $errorLogFile
+			exit 1
+		fi
+	fi
+done
