Remove `SKIP_INSTALL`; Not required

diff --git a/root-fs/app/bin/run-installation b/root-fs/app/bin/run-installation
--- a/root-fs/app/bin/run-installation
+++ b/root-fs/app/bin/run-installation
@@ -1,9 +1,8 @@
 #!/bin/bash
 
-if [ -n "$SKIP_INSTALL" ]; then
-	echo "#############################################"
-	echo "🚫 Skipping installation"
-	exit 0
+if [ ! -w /data ]; then
+	echo "ERROR: /data is not writable"
+	exit 1
 fi
 
 echo ""
